### PR TITLE
Fix bug causing ListView to disappear

### PR DESCRIPTION
**Pull request by RoeReRe**
image

Optional dosage fields now cause NA to show.

### CODE REVIEW

**Comment by RoeReRe** [comment]
Would you rather "Not Applicable" or still a way to display the consumption count @ChongWeiJie29

**Comment by ChongWeiJie29** [comment]
Displaying the consumption count wld be good, so ppl can track how many they take

**Review by shyanyong — APPROVED** [review]
LGTM

**Review by ChongWeiJie29 — COMMENTED** [review]
LGTM

**Review by ChongWeiJie29 — APPROVED** [review]
LGTM

**Pull request merged**
