### PR TITLE
Add take command

### PR DESCRIPTION
**Pull request by jingyu987**
Add Take Command

This commit adds a new command, take to the application. The take command allows users to take prescriptions given that there is enough stock. Does not limit the user from taking a medication if it is completed or if the consumption count is greater than the required amount. This is because if a user accidentally takes a medication when it is completed or takes too many, it should still allow the user to track how much the user overdosed by. LMK if it should be otherwise.

Still unsure how to implement resetting the consumption count i.e. for daily medication consumption count should be reset daily.

### CODE REVIEW

**Review by shyanyong — DISMISSED** [review]
LGTM!

**Comment by RoeReRe** [comment]
Seems to be because of the new `consumption` field not being included in the constructor for `prescription` in the test cases.

**Review by RoeReRe — APPROVED** [review]
LGTM. Tyvm!

**Review by shyanyong — APPROVED** [review]
LGTM

**Pull request merged**
