### PR TITLE
Add find command

### PR DESCRIPTION
**Pull request by TeeRenJing**
Lets add find command to search for prescriptions by name.

### CODE REVIEW

**Review by shyanyong — APPROVED** [review]
LGTM

**Review by jingyu987 — APPROVED** [review]
LGTM can merge once CI passes

**Review by ChongWeiJie29 — CHANGES_REQUESTED** [review]
Fix ur checkstyle boss

**Review by ChongWeiJie29 — APPROVED** [review]
LGTM

**Pull request merged**
