### PR TITLE
V1.3 GUI

### PR DESCRIPTION
**Pull request by RoeReRe**
I have refactored the GUI into the following.

gui

There are two motivating factors for this:

1. Our commands are long. It would be good to have a tall output box to show the example syntaxes. So instead of having a long unreadable line of `Example: add mn/Aspirin d/1 f/Daily sd/01/08/2023 ed/25/12/2023 exd/01/01/2024 ts/100 n/Test note`, we can break the parameters down into lines and display on the LHS. **These line breaks have not been implemented yet.**
2. To allow for better readability of the prescription, I have broken the list down to the RHS and made it (hopefully) cleaner.

The consumption will automatically update to red or green depending on the status.

I have also added more sample data into `SampleData.util` to test the scroll bar.

**I need yall to help pull this into your local and try run the GUI and test. JavaFX doesn't inherently support responsive UI that adjust properly to different screen sizes so I tried my best to work around it already.** As an intended feature, you cannot resize or move the application at all. Everything is scaled to the centered and resized to your screen size upon start up.

### CODE REVIEW

**Comment by RoeReRe** [comment]
We can ignore codecov in this case right? How do we even test the UI.

**Review by shyanyong — APPROVED** [review]
LGTM

**Comment by shyanyong** [comment]
> We can ignore codecov in this case right? How do we even test the UI.

Yup seems like other groups also not testing for UI.  Writing some test cases for other files to make up for the codecov

**Review by ChongWeiJie29 — APPROVED** [review]
LGTM

**Pull request merged**
