### PR TITLE
Add logic to label behaviour

### PR DESCRIPTION
**Pull request by RoeReRe**
Expiry Date and Total Stock header now turns Red upon the condition specified in `IsAboutToExpirePredicate` and `IsLowInStockPredicate`. This is updated whenever a Add, Take, Untake or Edit command is executed.

Does this break the abstraction barrier between frontend and backend? I can't think of any other implementations....

EDIT: CodeCov no choice uh....

### CODE REVIEW

**Comment by ChongWeiJie29** [comment]
Do you wanna consider a different kind of implementation

For eg. Stock has its own isLow boolean attribute, so u se the lowStockPredicate there. Similar for expiry date, it has its own closeToExpire boolean attribute. Then whenever u need to set the prescription card (setText or wtv), can check whether stock.isLow

**Review by shyanyong — APPROVED** [review]
LGTM

**Comment by RoeReRe** [comment]
> Do you wanna consider a different kind of implementation
> 
> For eg. Stock has its own isLow boolean attribute, so u se the lowStockPredicate there. Similar for expiry date, it has its own closeToExpire boolean attribute. Then whenever u need to set the prescription card (setText or wtv), can check whether stock.isLow

Will still be the same thing right? `PrescriptionCard` inevitably references the logic. Not much difference other than this causing more regression.

**Comment by ChongWeiJie29** [comment]
I mean, i think its less coupling. Cuz prescription card already uses stock/expiry date when setting text. So can use their attribute directly. Whereas here, in PrescriptionCard class ure doing a logic check by using a predicate defined all the way in model

**Review by ChongWeiJie29 — APPROVED** [review]
lgtm

**Pull request merged**
