### PR TITLE
fix date not exist bugs

### PR DESCRIPTION
**Pull request by shyanyong**

### CODE REVIEW

**Comment by shyanyong** [comment]
Changed method to throw when invalid dates inputted.  Uses localdate methods.
Added test cases for date parsing.  Checks for all the invalid dates (31/02/2023) including leap years and months less than 31 days.

**Review by ChongWeiJie29 — APPROVED** [review]
LGTM

**Review by TeeRenJing — APPROVED** [review]
LGTM

**Comment by shyanyong** [comment]
codecov is a scam.
image
image

**Pull request merged**
