### PR TITLE
add basic reminder command

### PR DESCRIPTION
**Pull request by shyanyong**

### CODE REVIEW

**Review by ChongWeiJie29 — APPROVED** [review]
LGTM

**Comment by ChongWeiJie29** [comment]
Yep this basic reminder feature works. We will work out to implement the auto-reminder feature along the way soon

**Review by RoeReRe — APPROVED** [review]
lgtm. But two questions for the long term:

1. This means for now theres no ordering? It will just be low in stock and about to expiry mixed together.

2. Maybe increase the low in stock to be proportional to total stock or dosage instead.

**Comment by shyanyong** [comment]
> lgtm. But two questions for the long term:
> 
> 1. This means for now theres no ordering? It will just be low in stock and about to expiry mixed together.
> 2. Maybe increase the low in stock to be proportional to total stock or dosage instead.

1.for this baseline i mixed it together first.  I already created the predicates for both so it can be easily transitioned to splitting into those that are about to expire and those that are low in stock
2. for this do you mean we remind them when they have (something like 3 takes left e.g. 4 pills per dose -> they have 12 pills left then we remind them)

**Comment by RoeReRe** [comment]
> > lgtm. But two questions for the long term:
> > 
> > 1. This means for now theres no ordering? It will just be low in stock and about to expiry mixed together.
> > 2. Maybe increase the low in stock to be proportional to total stock or dosage instead.
> 
> 1.for this baseline i mixed it together first. I already created the predicates for both so it can be easily transitioned to splitting into those that are about to expire and those that are low in stock 2. for this do you mean we remind them when they have (something like 3 takes left e.g. 4 pills per dose -> they have 12 pills left then we remind them)

Yup, was thinking instead of setting it to 10 absolutely. We can do maybe dosage x 7 days. Though non-issue for now.

**Pull request merged**
